k8s_version: "1.36.5"
k8s_minor: "{{ k8s_version.split('.')[:2] | join('.') }}"
helm_version: "3.22.0"
calico_version: "3.33.0"
local_path_version: "0.0.37"
metallb_version: "0.16.1"
gateway_api_version: "1.6.2"
envoy_gateway_version: "1.9.2"
cert_manager_version: "1.21.2"
kube_prometheus_stack_version: "91.9.0"
loki_chart_version: "18.13.7"
fluentd_image: "grafana/fluent-plugin-loki:3.7.8"
nginx_image: "nginxinc/nginx-unprivileged:1.30.5-alpine"
nginx_exporter_image: "nginx/nginx-prometheus-exporter:1.5.3"
app_namespace: "demo"

pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"

node_ip: "{{ ansible_default_ipv4.address }}"
base_domain: "{{ node_ip | replace('.', '-') }}.nip.io"
deploy_user: "{{ lookup('env', 'USER') }}"
kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
